package metier;
// Generated 8 fevr. 2020 12:38:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategorieSeance generated by hbm2java
 */
public class CategorieSeance  implements java.io.Serializable {


     private Integer idCategorieSeance;
     private String nomCategorieSeance;
     private String descriptionCategorieSeance;
     private Set seances = new HashSet(0);

    public CategorieSeance() {
    }

	
    public CategorieSeance(String nomCategorieSeance) {
        this.nomCategorieSeance = nomCategorieSeance;
    }
    public CategorieSeance(String nomCategorieSeance, String descriptionCategorieSeance, Set seances) {
       this.nomCategorieSeance = nomCategorieSeance;
       this.descriptionCategorieSeance = descriptionCategorieSeance;
       this.seances = seances;
    }
   
    public Integer getIdCategorieSeance() {
        return this.idCategorieSeance;
    }
    
    public void setIdCategorieSeance(Integer idCategorieSeance) {
        this.idCategorieSeance = idCategorieSeance;
    }
    public String getNomCategorieSeance() {
        return this.nomCategorieSeance;
    }
    
    public void setNomCategorieSeance(String nomCategorieSeance) {
        this.nomCategorieSeance = nomCategorieSeance;
    }
    public String getDescriptionCategorieSeance() {
        return this.descriptionCategorieSeance;
    }
    
    public void setDescriptionCategorieSeance(String descriptionCategorieSeance) {
        this.descriptionCategorieSeance = descriptionCategorieSeance;
    }
    public Set getSeances() {
        return this.seances;
    }
    
    public void setSeances(Set seances) {
        this.seances = seances;
    }




}


