package metier;
// Generated 8 fevr. 2020 16:33:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * CategorieExercice generated by hbm2java
 */
public class CategorieExercice  implements java.io.Serializable {


     private Integer idCategorieExercice;
     private String nomCategorieExercice;
     private String descriptionCategorieExercice;
     private Set exercices = new HashSet(0);

    public CategorieExercice() {
    }

	
    public CategorieExercice(String nomCategorieExercice) {
        this.nomCategorieExercice = nomCategorieExercice;
    }

    public CategorieExercice(Integer idCategorieExercice, String nomCategorieExercice) {
        this.idCategorieExercice = idCategorieExercice;
        this.nomCategorieExercice = nomCategorieExercice;
    }
    
    
    public CategorieExercice(String nomCategorieExercice, String descriptionCategorieExercice, Set exercices) {
       this.nomCategorieExercice = nomCategorieExercice;
       this.descriptionCategorieExercice = descriptionCategorieExercice;
       this.exercices = exercices;
    }
   
    public Integer getIdCategorieExercice() {
        return this.idCategorieExercice;
    }
    
    public void setIdCategorieExercice(Integer idCategorieExercice) {
        this.idCategorieExercice = idCategorieExercice;
    }
    public String getNomCategorieExercice() {
        return this.nomCategorieExercice;
    }
    
    public void setNomCategorieExercice(String nomCategorieExercice) {
        this.nomCategorieExercice = nomCategorieExercice;
    }
    public String getDescriptionCategorieExercice() {
        return this.descriptionCategorieExercice;
    }
    
    public void setDescriptionCategorieExercice(String descriptionCategorieExercice) {
        this.descriptionCategorieExercice = descriptionCategorieExercice;
    }
    public Set getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set exercices) {
        this.exercices = exercices;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 17 * hash + Objects.hashCode(this.idCategorieExercice);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CategorieExercice other = (CategorieExercice) obj;
        if (!Objects.equals(this.nomCategorieExercice, other.nomCategorieExercice)) {
            return false;
        }
        if (!Objects.equals(this.descriptionCategorieExercice, other.descriptionCategorieExercice)) {
            return false;
        }
        if (!Objects.equals(this.idCategorieExercice, other.idCategorieExercice)) {
            return false;
        }
        if (!Objects.equals(this.exercices, other.exercices)) {
            return false;
        }
        return true;
    }

    public void addExercice(Exercice e) {
        exercices.add(e);
        e.getCategorieExercices().add(this);
    }


}


