package metier;
// Generated 8 févr. 2020 12:38:47 by Hibernate Tools 4.3.1



/**
 * ContenirExerciceId generated by hbm2java
 */
public class ContenirExerciceId  implements java.io.Serializable {


     private int idExercice;
     private int idSeance;
     private int numOrdre;

    public ContenirExerciceId() {
    }

    public ContenirExerciceId(int idExercice, int idSeance, int numOrdre) {
       this.idExercice = idExercice;
       this.idSeance = idSeance;
       this.numOrdre = numOrdre;
    }
   
    public int getIdExercice() {
        return this.idExercice;
    }
    
    public void setIdExercice(int idExercice) {
        this.idExercice = idExercice;
    }
    public int getIdSeance() {
        return this.idSeance;
    }
    
    public void setIdSeance(int idSeance) {
        this.idSeance = idSeance;
    }
    public int getNumOrdre() {
        return this.numOrdre;
    }
    
    public void setNumOrdre(int numOrdre) {
        this.numOrdre = numOrdre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContenirExerciceId) ) return false;
		 ContenirExerciceId castOther = ( ContenirExerciceId ) other; 
         
		 return (this.getIdExercice()==castOther.getIdExercice())
 && (this.getIdSeance()==castOther.getIdSeance())
 && (this.getNumOrdre()==castOther.getNumOrdre());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdExercice();
         result = 37 * result + this.getIdSeance();
         result = 37 * result + this.getNumOrdre();
         return result;
   }   


}


