package metier;
// Generated 8 févr. 2020 12:38:47 by Hibernate Tools 4.3.1



/**
 * ContenirExercice generated by hbm2java
 */
public class ContenirExercice  implements java.io.Serializable {


     private ContenirExerciceId id;
     private Exercice exercice;
     private Seance seance;
     private Integer nbRepetitions;
     private Integer nbOccurenceRepetitions;
     private Long tempsPause;
     private Long duree;

    public ContenirExercice() {
    }

	
    public ContenirExercice(ContenirExerciceId id, Exercice exercice, Seance seance) {
        this.id = id;
        this.exercice = exercice;
        this.seance = seance;
    }
    public ContenirExercice(ContenirExerciceId id, Exercice exercice, Seance seance, Integer nbRepetitions, Integer nbOccurenceRepetitions, Long tempsPause, Long duree) {
       this.id = id;
       this.exercice = exercice;
       this.seance = seance;
       this.nbRepetitions = nbRepetitions;
       this.nbOccurenceRepetitions = nbOccurenceRepetitions;
       this.tempsPause = tempsPause;
       this.duree = duree;
    }
   
    public ContenirExerciceId getId() {
        return this.id;
    }
    
    public void setId(ContenirExerciceId id) {
        this.id = id;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Integer getNbRepetitions() {
        return this.nbRepetitions;
    }
    
    public void setNbRepetitions(Integer nbRepetitions) {
        this.nbRepetitions = nbRepetitions;
    }
    public Integer getNbOccurenceRepetitions() {
        return this.nbOccurenceRepetitions;
    }
    
    public void setNbOccurenceRepetitions(Integer nbOccurenceRepetitions) {
        this.nbOccurenceRepetitions = nbOccurenceRepetitions;
    }
    public Long getTempsPause() {
        return this.tempsPause;
    }
    
    public void setTempsPause(Long tempsPause) {
        this.tempsPause = tempsPause;
    }
    public Long getDuree() {
        return this.duree;
    }
    
    public void setDuree(Long duree) {
        this.duree = duree;
    }




}


