package metier;
// Generated 8 fevr. 2020 16:33:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * ObjectifExercice generated by hbm2java
 */
public class ObjectifExercice  implements java.io.Serializable {


     private Integer idObjectifExercice;
     private String nomObjectifExercice;
     private String descriptionObjectifExercice;
     private Set exercices = new HashSet(0);

    public ObjectifExercice() {
    }

	
    public ObjectifExercice(String nomObjectifExercice) {
        this.nomObjectifExercice = nomObjectifExercice;
    }
    public ObjectifExercice(String nomObjectifExercice, String descriptionObjectifExercice, Set exercices) {
       this.nomObjectifExercice = nomObjectifExercice;
       this.descriptionObjectifExercice = descriptionObjectifExercice;
       this.exercices = exercices;
    }
   
    public Integer getIdObjectifExercice() {
        return this.idObjectifExercice;
    }
    
    public void setIdObjectifExercice(Integer idObjectifExercice) {
        this.idObjectifExercice = idObjectifExercice;
    }
    public String getNomObjectifExercice() {
        return this.nomObjectifExercice;
    }
    
    public void setNomObjectifExercice(String nomObjectifExercice) {
        this.nomObjectifExercice = nomObjectifExercice;
    }
    public String getDescriptionObjectifExercice() {
        return this.descriptionObjectifExercice;
    }
    
    public void setDescriptionObjectifExercice(String descriptionObjectifExercice) {
        this.descriptionObjectifExercice = descriptionObjectifExercice;
    }
    public Set getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set exercices) {
        this.exercices = exercices;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.idObjectifExercice);
        hash = 59 * hash + Objects.hashCode(this.nomObjectifExercice);
        hash = 59 * hash + Objects.hashCode(this.descriptionObjectifExercice);
        hash = 59 * hash + Objects.hashCode(this.exercices);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ObjectifExercice other = (ObjectifExercice) obj;
        if (!Objects.equals(this.nomObjectifExercice, other.nomObjectifExercice)) {
            return false;
        }
        if (!Objects.equals(this.descriptionObjectifExercice, other.descriptionObjectifExercice)) {
            return false;
        }
        if (!Objects.equals(this.idObjectifExercice, other.idObjectifExercice)) {
            return false;
        }
        if (!Objects.equals(this.exercices, other.exercices)) {
            return false;
        }
        return true;
    }

    /**
     * Fonction d'ajout 
     */

    public void addExercice(Exercice e) {
        exercices.add(e);
        e.getObjectifExercices().add(this);
    }

}


