package metier;
// Generated 8 févr. 2020 12:38:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ObjectifExercice generated by hbm2java
 */
public class ObjectifExercice  implements java.io.Serializable {


     private Integer idObjectifExercice;
     private String nomObjectifExercice;
     private String descriptionObjectifExercice;
     private Set exercices = new HashSet(0);

    public ObjectifExercice() {
    }

	
    public ObjectifExercice(String nomObjectifExercice) {
        this.nomObjectifExercice = nomObjectifExercice;
    }
    public ObjectifExercice(String nomObjectifExercice, String descriptionObjectifExercice, Set exercices) {
       this.nomObjectifExercice = nomObjectifExercice;
       this.descriptionObjectifExercice = descriptionObjectifExercice;
       this.exercices = exercices;
    }
   
    public Integer getIdObjectifExercice() {
        return this.idObjectifExercice;
    }
    
    public void setIdObjectifExercice(Integer idObjectifExercice) {
        this.idObjectifExercice = idObjectifExercice;
    }
    public String getNomObjectifExercice() {
        return this.nomObjectifExercice;
    }
    
    public void setNomObjectifExercice(String nomObjectifExercice) {
        this.nomObjectifExercice = nomObjectifExercice;
    }
    public String getDescriptionObjectifExercice() {
        return this.descriptionObjectifExercice;
    }
    
    public void setDescriptionObjectifExercice(String descriptionObjectifExercice) {
        this.descriptionObjectifExercice = descriptionObjectifExercice;
    }
    public Set getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set exercices) {
        this.exercices = exercices;
    }




}


