package metier;
// Generated 8 fevr. 2020 12:38:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profil generated by hbm2java
 */
public class Profil  implements java.io.Serializable {


     private Integer idProfil;
     private String nomProfil;
     private Set programmes = new HashSet(0);

    public Profil() {
    }

	
    public Profil(String nomProfil) {
        this.nomProfil = nomProfil;
    }
    public Profil(String nomProfil, Set programmes) {
       this.nomProfil = nomProfil;
       this.programmes = programmes;
    }
   
    public Integer getIdProfil() {
        return this.idProfil;
    }
    
    public void setIdProfil(Integer idProfil) {
        this.idProfil = idProfil;
    }
    public String getNomProfil() {
        return this.nomProfil;
    }
    
    public void setNomProfil(String nomProfil) {
        this.nomProfil = nomProfil;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }




}


