package metier;
// Generated 8 fevr. 2020 16:33:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Programme generated by hbm2java
 */
public class Programme  implements java.io.Serializable {


     private Integer idProgramme;
     private Profil profil;
     private String nomProgramme;
     private Set contenirSeances = new HashSet(0);

    public Programme() {
    }

	
    public Programme(String nomProgramme) {
        this.nomProgramme = nomProgramme;
    }
    public Programme(Profil profil, String nomProgramme, Set contenirSeances) {
       this.profil = profil;
       this.nomProgramme = nomProgramme;
       this.contenirSeances = contenirSeances;
    }
   
    public Integer getIdProgramme() {
        return this.idProgramme;
    }
    
    public void setIdProgramme(Integer idProgramme) {
        this.idProgramme = idProgramme;
    }
    public Profil getProfil() {
        return this.profil;
    }
    
    public void setProfil(Profil profil) {
        this.profil = profil;
    }
    public String getNomProgramme() {
        return this.nomProgramme;
    }
    
    public void setNomProgramme(String nomProgramme) {
        this.nomProgramme = nomProgramme;
    }
    public Set getContenirSeances() {
        return this.contenirSeances;
    }
    
    public void setContenirSeances(Set contenirSeances) {
        this.contenirSeances = contenirSeances;
    }




}


