package metier;
// Generated 8 fevr. 2020 16:33:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Seance generated by hbm2java
 */
public class Seance  implements java.io.Serializable {


     private Integer idSeance;
     private Difficulte difficulte;
     private String nomSeance;
     private String typeSeance;
     private Set contenirExercices = new HashSet(0);
     private Set categorieSeances = new HashSet(0);
     private Set contenirSeances = new HashSet(0);

    public Seance() {
    }
	
    public Seance(String nomSeance, String typeSeance) {
        this.nomSeance = nomSeance;
        this.typeSeance = typeSeance;
    }
    public Seance(Difficulte difficulte, String nomSeance, String typeSeance, Set contenirExercices, Set categorieSeances, Set contenirSeances) {
       this.difficulte = difficulte;
       this.nomSeance = nomSeance;
       this.typeSeance = typeSeance;
       this.contenirExercices = contenirExercices;
       this.categorieSeances = categorieSeances;
       this.contenirSeances = contenirSeances;
    }

    public Seance(Integer idSeance, Difficulte difficulte, String nomSeance, String typeSeance) {
        this.idSeance = idSeance;
        this.difficulte = difficulte;
        this.nomSeance = nomSeance;
        this.typeSeance = typeSeance;
    }
    
   
    public Integer getIdSeance() {
        return this.idSeance;
    }
    
    public void setIdSeance(Integer idSeance) {
        this.idSeance = idSeance;
    }
    public Difficulte getDifficulte() {
        return this.difficulte;
    }
    
    public void setDifficulte(Difficulte difficulte) {
        this.difficulte = difficulte;
    }
    public String getNomSeance() {
        return this.nomSeance;
    }
    
    public void setNomSeance(String nomSeance) {
        this.nomSeance = nomSeance;
    }
    public String getTypeSeance() {
        return this.typeSeance;
    }
    
    public void setTypeSeance(String typeSeance) {
        this.typeSeance = typeSeance;
    }
    public Set getContenirExercices() {
        return this.contenirExercices;
    }
    
    public void setContenirExercices(Set contenirExercices) {
        this.contenirExercices = contenirExercices;
    }
    public Set getCategorieSeances() {
        return this.categorieSeances;
    }
    
    public void setCategorieSeances(Set categorieSeances) {
        this.categorieSeances = categorieSeances;
    }
    public Set getContenirSeances() {
        return this.contenirSeances;
    }
    
    public void setContenirSeances(Set contenirSeances) {
        this.contenirSeances = contenirSeances;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 29 * hash + Objects.hashCode(this.idSeance);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Seance other = (Seance) obj;
        if (!Objects.equals(this.idSeance, other.idSeance)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Seance{" + "idSeance=" + idSeance + ", difficulte=" + difficulte + ", nomSeance=" + nomSeance + ", typeSeance=" + typeSeance + ", contenirExercices=" + contenirExercices + ", categorieSeances=" + categorieSeances + ", contenirSeances=" + contenirSeances + '}';
    }
    




}


